### ISSUE TITLE
Incorrect Results

### ISSUE THREAD

**Issue by isamhazen** [mvirgo/Unscented-Kalman-Filter#1]
Hi @mvirgo , I tried your code to reproduce the results. But when I ran the code, I obtained very incorrect results (like values in Millions for UKF estimation). Is there a problem in the original code, or am I missing something?
Thanks

**Comment by mvirgo** [comment]
Hi there! I actually jacked this up when I re-arranged a few things in what was the latest commit you saw - I have now reverted that commit. I need to change this up to work with the new version of the project anyway.
